{"email":"user@example.com","error":{"message":"No metadata for \"User\" was found.","stack":"EntityMetadataNotFoundError: No metadata for \"User\" was found.\n    at DataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)\n    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)\n    at Repository.findOne (/app/node_modules/typeorm/repository/Repository.js:255:42)\n    at RegisterUserHandler.execute (/app/dist/apps/api-gateway/main.js:731:56)\n    at CommandBus.execute (/app/node_modules/@nestjs/cqrs/dist/command-bus.js:56:24)\n    at AuthController.register (/app/dist/apps/api-gateway/main.js:179:50)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"},"level":"error","message":"Registration failed Registration failed","service":"auth","timestamp":"2025-04-12T16:42:37.515Z"}
{"email":"user@example.com","error":{"message":"No metadata for \"User\" was found.","stack":"EntityMetadataNotFoundError: No metadata for \"User\" was found.\n    at DataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)\n    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)\n    at Repository.findOne (/app/node_modules/typeorm/repository/Repository.js:255:42)\n    at RegisterUserHandler.execute (/app/dist/apps/api-gateway/main.js:731:56)\n    at CommandBus.execute (/app/node_modules/@nestjs/cqrs/dist/command-bus.js:56:24)\n    at AuthController.register (/app/dist/apps/api-gateway/main.js:179:50)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"},"level":"error","message":"Registration failed Registration failed","service":"auth","timestamp":"2025-04-12T16:42:46.760Z"}
{"email":"user@example.com","error":{"message":"No metadata for \"User\" was found.","stack":"EntityMetadataNotFoundError: No metadata for \"User\" was found.\n    at DataSource.getMetadata (/app/node_modules/typeorm/data-source/DataSource.js:304:19)\n    at get metadata [as metadata] (/app/node_modules/typeorm/repository/Repository.js:15:40)\n    at Repository.findOne (/app/node_modules/typeorm/repository/Repository.js:255:42)\n    at RegisterUserHandler.execute (/app/dist/apps/api-gateway/main.js:731:56)\n    at CommandBus.execute (/app/node_modules/@nestjs/cqrs/dist/command-bus.js:56:24)\n    at AuthController.register (/app/dist/apps/api-gateway/main.js:179:50)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"},"level":"error","message":"Registration failed Registration failed","service":"auth","timestamp":"2025-04-12T16:45:11.924Z"}
{"email":"user2@example.com","error":{"message":"Invalid credentials","stack":"UnauthorizedException: Invalid credentials\n    at LoginUserHandler.execute (/app/dist/apps/api-gateway/main.js:1022:19)\n    at async AuthController.login (/app/dist/apps/api-gateway/main.js:221:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"},"level":"error","message":"Login failed Login failed","service":"auth","timestamp":"2025-04-12T17:11:54.580Z"}
{"email":"user3@example.com","error":{"message":"Invalid credentials","stack":"UnauthorizedException: Invalid credentials\n    at LoginUserHandler.execute (/app/dist/apps/api-gateway/main.js:1018:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async AuthController.login (/app/dist/apps/api-gateway/main.js:221:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17"},"level":"error","message":"Login failed Login failed","service":"auth","timestamp":"2025-04-12T17:12:00.644Z"}
